Repository moderncv/moderncv, pull requests merged in 2024-05, with the labels that each got.

#151 make colors user adjustable.
  CHANGELOG
  moderncv.cls
  moderncvbodyi.sty
  moderncvbodyiii.sty
  moderncvbodyiv.sty
  moderncvbodyv.sty
  moderncvfooti.sty
  moderncvheadi.sty
  moderncvheadii.sty
  moderncvheadiii.sty
  moderncvheadiv.sty
  moderncvheadv.sty
  moderncvheadvi.sty
  moderncvskillmatrix.sty
  moderncvstylebanking.sty
  moderncvstylecasual.sty
  moderncvstyleclassic.sty
  moderncvstyleempty.sty
  moderncvstylefancy.sty
  moderncvstyleoldstyle.sty
  template.tex
Labels: documentation, enhancement

#150 make hidden head options available
  CHANGELOG
  moderncvheadvi.sty
  moderncvstylebanking.sty
  moderncvstylecasual.sty
  moderncvstyleclassic.sty
  moderncvstylefancy.sty
  moderncvstyleoldstyle.sty
Labels: enhancement

#187 Add documentation for "contemporary" style to user guide
  .gitignore
  manual/moderncv_userguide.pdf
  manual/moderncv_userguide.tex
Labels: documentation

#189 Restore previous cvlistitem spacing
  moderncvbodyi.sty
  moderncvbodyiii.sty
  moderncvbodyiv.sty
  moderncvbodyv.sty
  moderncvbodyvi.sty
Labels: bug

#177 Feature/cvtripleitem
  CHANGELOG
  manual/moderncv_userguide.pdf
  manual/moderncv_userguide.tex
  moderncv.cls
  moderncvbodyi.sty
  moderncvbodyiii.sty
  moderncvbodyiv.sty
  moderncvbodyv.sty
  moderncvbodyvi.sty
  template.tex
Labels: enhancement
